application: museum-partner
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: static/stylesheets

- url: /js
  static_dir: static/js

- url: /images
  static_dir: static/images

- url: /images/(.*)
  static_files: static/images/\1
  upload: static/images/(.*)
  
- url: /.*
  script: main.py
  
builtins:
- datastore_admin: on