application: museum-partner
version: 1
runtime: python
api_version: 1

handlers:
- url: /static/css
  static_dir: static/css

- url: /static/js
  static_dir: static/js
  
- url: /.*
  script: main.py
  
builtins:
- datastore_admin: on